### PR TITLE
Users locations

### PR DESCRIPTION
**Pull request by Mei152**
I am at least putting this out here so I can start another branch. I don't want to let things get too carried away again.

Your suggestion to work on master, and put the ticket numbers in the commit messages was killing me.  I was having to modify commit messages often. Unless you feel otherwise, I think the project will be stable enough from here on out to resume the original protocol.

### CODE REVIEW

**Comment by mkwiatkowski** [comment]
> Your suggestion to work on master, and put the ticket numbers in the commit messages was killing me. I was having to modify commit messages often.

Why is that? You were simply forgetting about it? I still see *a lot* of commits here without any associated ticket number.

Associating commits with tickets is a practice that pays off later on, when you need to trace back a bug source or reason for some design decision made months back. It's useful regardless if you use a pull request or not.

If you are happy with this code then merge it, so you can start a new branch off master.

**Comment by Mei152** [comment]
> Why is that? You were simply forgetting about it?

I can't argue with that. Just because it is difficult for me now doesn't mean I can't learn to make it habitual.

Just to be clear, do you want me to create a ticket for **everything** I do, no matter how trivial?

**Comment by mkwiatkowski** [comment]
> Just to be clear, do you want me to create a ticket for everything I do, no matter how trivial?

No, trivial things don't need a ticket. For example, commits like c0bda743bec5d80b20b0789a531bb8158a517c83 or 95c394e02e7fe1814c32c8af7cb95acf8b296b8b wouldn't need a ticket, although they could also be part of some ticket (e.g. if some small change or refactoring leads to or is effect of some previous changes related to a ticket).

Use your own judgment and err on the side of creating more tickets.

Another thing is that if you mark your tickets properly you don't need to go back and add "Completed with commit X" comments. For example in issue #4 you added a comment even though github already linked the commit with the issue due to a good commit message:

github-links-commits

On top of that, if you say in your commit message "fixes #4" then github will close the issue for you automatically. See https://help.github.com/articles/closing-issues-via-commit-messages/ for more details.

**Comment by Mei152** [comment]
I was excited to try this out, but it didn't work for me. Not sure why.
035d03254b938c88018e230cbe91cc4fe794bc14 should have closed issue #50

**Comment by mkwiatkowski** [comment]
See https://github.com/Mei152/hours_import/issues/42#issuecomment-187627762

**Pull request merged**
